/// Migrate a bash/sh script to dgsh syntax.
/// Returns the converted source code.
#[must_use]
pub fn migrate_sh_to_dgsh(source: &str) -> String {
    let mut ctx = MigrateContext::new();
    let lines: Vec<&str> = source.lines().collect();

    // First pass: collect user-defined function names
    for line in &lines {
        let trimmed = line.trim();
        if let Some(name) = parse_function_def(trimmed) {
            ctx.user_functions.push(name.to_ascii_lowercase());
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim();
        i += 1;

        // Skip shebang
        if trimmed.starts_with("#!") && ctx.output.is_empty() {
            ctx.push_line("# Auto-generated by dgsh -migrate");
            ctx.push_line("# This file may contain errors and should be reviewed manually.");
            ctx.push_line("# Lines marked with '# TODO' require manual adjustment.");
            ctx.push_line("");
            continue;
        }

        // Heredoc collection mode
        if let Some(ref marker) = ctx.heredoc_marker.clone() {
            if trimmed == marker {
                // End of heredoc — emit as """ string
                let content = ctx.heredoc_lines.join("\n");
                let cmd = ctx.heredoc_cmd.clone();
                ctx.heredoc_marker = None;
                ctx.heredoc_lines.clear();
                ctx.heredoc_cmd.clear();
                if cmd.is_empty() {
                    ctx.push_line("\"\"\"");
                    ctx.push_raw(&content);
                    ctx.push_line("\"\"\"");
                } else {
                    ctx.push_line(&format!("# Heredoc content for: {cmd}"));
                    ctx.push_line("_heredoc_content = \"\"\"");
                    ctx.push_raw(&content);
                    ctx.push_line("\"\"\"");
                    let (cmd_stripped, _) = strip_redirects(&cmd);
                    let converted = convert_command(cmd_stripped.trim());
                    ctx.push_line(&format!("# TODO: pass _heredoc_content to: {converted}"));
                }
            } else {
                ctx.heredoc_lines.push(line.to_string());
            }
            continue;
        }

        // Empty lines
        if trimmed.is_empty() {
            ctx.push_raw("");
            continue;
        }

        // Comments
        if trimmed.starts_with('#') {
            ctx.push_indented(trimmed);
            continue;
        }

        // Process the line
        ctx.process_line(trimmed);
    }

    // Close any remaining open blocks
    while ctx.indent_level > 0 {
        ctx.indent_level -= 1;
    }

    ctx.output.join("\n") + "\n"
}

/// Pure dgsh builtins — these don't exist as executables, so they get !! in migrated code
const PURE_BUILTINS: &[&str] = &[
    // I/O
    "print", "println", "errprint", "errprintln", "input",
    // Types
    "str", "int", "float", "bool", "type",
    // Collections
    "len", "push", "pop", "has", "index", "flat", "unique", "zip",
    // Note: "sort" omitted — it's also an exe
    "range", "slice", "insert", "remove", "merge", "sum", "min", "max",
    "map", "filter", "reduce", "sort_by", "count", "any", "all",
    // Note: "find" omitted — it's also an exe (find command)
    // Strings
    "split", "join", "trim", "upper", "lower", "replace", "contains",
    "starts_with", "ends_with", "substr", "index_of", "pad_left", "pad_right",
    "repeat", "reverse", "chars", "match_all",
    // System (dgsh-only)
    "env", "env_set", "env_all", "os", "pid", "arch",
    "which", "args", "exec", "exec_in", "home", "refresh_env",
    // Filesystem (dgsh-only, not the exe versions)
    "exists", "is_file", "is_dir", "cwd", "ext", "abs", "filesize",
    // Math
    "abs_num", "ceil", "floor", "round", "sqrt", "pow", "log", "log10",
    "sin", "cos", "tan", "random", "random_int", "pi", "infinity",
    // DateTime
    "now", "timestamp", "date_format", "date_parse", "elapsed",
    // Formats
    "from_json", "to_json", "from_toml", "to_toml", "from_yaml", "to_yaml",
    "from_csv", "to_csv", "to_base64", "from_base64", "to_hex", "from_hex",
    "url_encode", "url_decode",
    // Network
    "http_get", "http_post", "http_put", "http_delete", "download", "hostname", "ip",
    // Hashing
    "md5", "sha256", "sha512", "uuid",
    // Threads
    "thread", "wait", "wait_all", "wait_any", "atomic",
    // File I/O (streaming)
    "open_file", "read_line", "read_chunk", "close_file",
    "byte_len", "byte_at", "byte_slice", "to_bytes", "from_bytes",
    "read_bytes", "write_bytes", "append_bytes", "bytes_from_list",
    // Terminal
    "set_color", "set_bg", "set_bold", "set_dim", "set_underline",
    "reset_style", "cursor_pos", "term_size",
    // Process
    "get_processes", "get_process_by_name", "get_process_by_id",
    "kill_process", "is_process_running",
    // Events
    "on_event",
];

/// These exist as both exe AND dgsh builtin — in migrated code they stay without modifier
/// because bash was calling the exe version
const _EXE_AVAILABLE: &[&str] = &[
    "read", "write", "append", "mkdir", "rm", "cp", "mv", "ls", "cd",
    "basename", "dirname", "glob", "tempfile", "tempdir",
    "sleep", "exit", "clear", "match",
];

struct MigrateContext {
    output: Vec<String>,
    indent_level: usize,
    /// Track if we're inside a case/esac
    in_case: bool,
    case_var: String,
    /// Pending loop update for C-style for (inserted before `done`)
    pending_loop_update: Option<String>,
    /// User-defined function names (collected in first pass)
    user_functions: Vec<String>,
    /// Heredoc end marker — when set, lines are collected as string content
    heredoc_marker: Option<String>,
    heredoc_lines: Vec<String>,
    heredoc_cmd: String,
}

impl MigrateContext {
    const fn new() -> Self {
        Self {
            output: Vec::new(),
            indent_level: 0,
            in_case: false,
            case_var: String::new(),
            pending_loop_update: None,
            user_functions: Vec::new(),
            heredoc_marker: None,
            heredoc_lines: Vec::new(),
            heredoc_cmd: String::new(),
        }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    fn push_raw(&mut self, s: &str) {
        self.output.push(s.to_string());
    }

    fn push_line(&mut self, s: &str) {
        let resolved = apply_resolution(s, &self.user_functions);
        self.output.push(format!("{}{resolved}", self.indent()));
    }

    fn push_indented(&mut self, s: &str) {
        self.output.push(format!("{}{s}", self.indent()));
    }

    fn process_line(&mut self, line: &str) {
        // Don't split on ; if line contains (( )) — C-style for loops
        if line.contains("((") || line.contains("))") {
            self.process_single(line);
            return;
        }
        // Handle semicolon-separated commands
        if line.contains(';') && !line.contains(";;") && !is_in_string(line, ';') {
            for part in split_on_semicolons(line) {
                let part = part.trim();
                if !part.is_empty() {
                    self.process_single(part);
                }
            }
            return;
        }
        self.process_single(line);
    }

    fn process_single(&mut self, line: &str) {
        if self.try_process_block_structure(line) {
            return;
        }
        if self.try_process_flow_control(line) {
            return;
        }
        self.process_command(line);
    }

    fn try_process_block_structure(&mut self, line: &str) -> bool {
        if line == "fi" || line == "fi;" {
            if self.indent_level > 0 { self.indent_level -= 1; }
            return true;
        }
        if line == "done" || line == "done;" {
            if let Some(update) = self.pending_loop_update.take() {
                self.push_line(&update);
            }
            if self.indent_level > 0 { self.indent_level -= 1; }
            return true;
        }
        if line == "esac" || line == "esac;" {
            if self.indent_level > 0 { self.indent_level -= 1; }
            if self.indent_level > 0 { self.indent_level -= 1; }
            self.in_case = false;
            return true;
        }
        if line == "}" {
            if self.indent_level > 0 { self.indent_level -= 1; }
            return true;
        }
        if line == "then" || line == "do" {
            return true;
        }
        if let Some(rest) = strip_prefix_word(line, "elif") {
            if self.indent_level > 0 { self.indent_level -= 1; }
            let cond = rest.trim_end_matches("then").trim_end_matches(';').trim();
            let cond = convert_condition(cond);
            self.push_line(&format!("else if {cond}"));
            self.indent_level += 1;
            return true;
        }
        if line == "else" {
            if self.indent_level > 0 { self.indent_level -= 1; }
            self.push_line("else");
            self.indent_level += 1;
            return true;
        }
        false
    }

    fn try_process_flow_control(&mut self, line: &str) -> bool {
        if let Some(rest) = strip_prefix_word(line, "if") {
            let rest = rest.trim_end_matches("then").trim_end_matches(';').trim();
            let cond = convert_condition(rest);
            self.push_line(&format!("if {cond}"));
            self.indent_level += 1;
            return true;
        }
        if let Some(rest) = strip_prefix_word(line, "for") {
            let rest = rest.trim_end_matches("do").trim_end_matches(';').trim();
            if let Some((var, iter)) = rest.split_once(" in ") {
                let var = var.trim();
                let iter = convert_for_iter(iter.trim());
                self.push_line(&format!("for {var} in {iter}"));
                self.indent_level += 1;
            } else {
                self.push_line(&format!("# TODO: migrate for loop: {line}"));
            }
            return true;
        }
        if line.starts_with("for ((") || line.starts_with("for((") {
            let start = line.find("((").unwrap_or(0) + 2;
            let end = line.rfind("))").unwrap_or(line.len());
            let inner = line[start..end].trim()
                .trim_end_matches("do").trim_end_matches(';').trim();
            let update = extract_c_for_update(line);
            let converted = convert_c_for(inner);
            for l in &converted { self.push_line(l); }
            self.pending_loop_update = update;
            self.indent_level += 1;
            return true;
        }
        if let Some(rest) = strip_prefix_word(line, "while") {
            let rest = rest.trim_end_matches("do").trim_end_matches(';').trim();
            let cond = convert_condition(rest);
            self.push_line(&format!("while {cond}"));
            self.indent_level += 1;
            return true;
        }
        if let Some(rest) = strip_prefix_word(line, "case") {
            let rest = rest.trim_end_matches("in").trim_end_matches(';').trim();
            let var = convert_expr(rest);
            self.push_line(&format!("match {var}"));
            self.indent_level += 1;
            self.in_case = true;
            self.case_var = var;
            return true;
        }
        if self.in_case {
            if line == ";;" {
                if self.indent_level > 0 { self.indent_level -= 1; }
                return true;
            }
            if let Some(paren_pos) = find_case_pattern_end(line) {
                let pattern = line[..paren_pos].trim_start_matches('(').trim();
                let rest = line[paren_pos+1..].trim();
                if pattern == "*" { self.push_line("_"); }
                else { self.push_line(&convert_case_pattern(pattern)); }
                self.indent_level += 1;
                let body = rest.trim_end_matches(";;").trim();
                if !body.is_empty() { self.process_line(body); }
                if rest.ends_with(";;") && self.indent_level > 0 { self.indent_level -= 1; }
                return true;
            }
        }
        if let Some(name) = parse_function_def(line) {
            self.push_raw(&format!("{}{}()", self.indent(), name));
            self.indent_level += 1;
            return true;
        }
        false
    }

    fn process_command(&mut self, line: &str) {
        if let Some(rest) = strip_prefix_word(line, "local") {
            let rest = rest.trim();
            if rest.chars().all(|c| c.is_alphanumeric() || c == '_') { return; }
            self.process_single(rest);
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "declare") {
            let rest = skip_declare_flags(rest);
            if !rest.is_empty() { self.process_single(rest); }
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "export") {
            if let Some((name, val)) = rest.split_once('=') {
                let val = convert_value(val.trim());
                self.push_line(&format!("env_set(\"{}\", {val})", name.trim()));
            } else {
                self.push_line(&format!("# TODO: export {rest}"));
            }
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "source") {
            self.push_line(&format!("import {}", convert_value(rest.trim())));
            return;
        }
        if let Some(rest) = line.strip_prefix(". ") {
            self.push_line(&format!("import {}", convert_value(rest.trim())));
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "echo") {
            self.process_echo(line, rest);
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "read") {
            let parts: Vec<&str> = rest.split_whitespace().collect();
            let var = parts.last().unwrap_or(&"line");
            if var.starts_with('$') || var.starts_with('-') || var.is_empty() {
                self.push_line(&format!("# TODO: migrate read: {line}"));
            } else {
                self.push_line(&format!("{var} = input()"));
            }
            return;
        }
        if line == "shift" || line.starts_with("shift ") {
            self.push_line("# TODO: shift — dgsh functions use named parameters, not positional $1/$2");
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "return") {
            let val = rest.trim();
            if val.is_empty() || val == "0" { self.push_line("return"); }
            else { self.push_line(&format!("return {}", convert_expr(val))); }
            return;
        }
        if let Some(rest) = strip_prefix_word(line, "exit") {
            let code = rest.trim();
            if code.is_empty() { self.push_line("exit(0)"); }
            else { self.push_line(&format!("exit({})", convert_expr(code))); }
            return;
        }
        if let Some((name, val)) = parse_assignment(line) {
            self.process_assignment(name, val);
            return;
        }
        self.process_special_or_command(line);
    }

    fn process_special_or_command(&mut self, line: &str) {
        if line.starts_with("((") && line.ends_with("))") {
            let inner = line[2..line.len()-2].trim();
            self.push_line(&convert_arithmetic_stmt(inner));
            return;
        }
        if line.contains(" | ") && !is_in_string(line, '|') {
            self.push_line(&convert_pipe_chain(line));
            return;
        }
        if line.contains("<<") && !line.contains("<<<") {
            let heredoc_marker = line.split("<<").nth(1).map_or("", |s| {
                s.trim().trim_matches('\'').trim_matches('"').trim()
            });
            if !heredoc_marker.is_empty() && heredoc_marker.chars().all(|c| c.is_alphanumeric() || c == '_') {
                let cmd_part = line.split("<<").next().unwrap_or("").trim();
                self.heredoc_marker = Some(heredoc_marker.to_string());
                self.heredoc_cmd = cmd_part.to_string();
                self.heredoc_lines.clear();
                return;
            }
        }
        if line.ends_with(" &") || line.ends_with("\t&") {
            let cmd = line[..line.len()-2].trim();
            self.push_line("# TODO: background process — use thread() instead");
            self.push_line(&format!("# {}", convert_command(cmd)));
            return;
        }
        if line.starts_with('(') && line.ends_with(')') && !line.starts_with("((") {
            let inner = &line[1..line.len()-1];
            self.push_line("# TODO: subshell — convert inner commands manually");
            self.push_line(&format!("# Original: {inner}"));
            return;
        }
        if line.contains("<<<") {
            self.push_line("# TODO: here-string — use exec_in() instead");
            self.push_line(&format!("# Original: {line}"));
            return;
        }
        let converted = convert_command_ctx(line, &self.user_functions);
        self.push_line(&converted);
    }

    fn process_echo(&mut self, line: &str, rest: &str) {
        if rest.contains(" | ") && !is_in_quotes(rest, '|') {
            self.push_line(&convert_pipe_chain(line));
            return;
        }
        let (rest, redirects) = strip_redirects(rest.trim());
        let rest = rest.trim();
        if let Some(after_n) = rest.strip_prefix("-n ") {
            self.push_line(&format!("print({})", convert_value(after_n.trim())));
        } else if let Some(after_e) = rest.strip_prefix("-e ") {
            self.push_line(&format!("println({})", convert_value(after_e.trim())));
        } else {
            let msg = convert_value(rest);
            if !redirects.is_empty() {
                let redirect = redirects.trim();
                if redirect == ">&2" || redirect.starts_with(">&2") {
                    self.push_line(&format!("errprintln({msg})"));
                    return;
                }
                if let Some(file) = redirect.strip_prefix(">>").map(str::trim_start) {
                    self.push_line(&format!("append({}, {msg})", convert_value(file.trim())));
                    return;
                }
                if let Some(file) = redirect.strip_prefix(">").map(str::trim_start) {
                    self.push_line(&format!("write({}, {msg})", convert_value(file.trim())));
                    return;
                }
            }
            self.push_line(&format!("println({msg})"));
        }
    }

    fn process_assignment(&mut self, name: &str, val: &str) {
        let val_trimmed = val.trim();
        if !val_trimmed.is_empty()
            && !val_trimmed.starts_with('"')
            && !val_trimmed.starts_with('\'')
            && !val_trimmed.starts_with("$(")
            && !val_trimmed.starts_with('`')
            && !val_trimmed.starts_with('(')
            && val_trimmed.contains(' ')
            && let Some(space_pos) = val_trimmed.find(' ')
        {
            let env_val = &val_trimmed[..space_pos];
            let cmd = &val_trimmed[space_pos+1..];
            self.push_line(&format!("env_set(\"{name}\", {})", convert_value(env_val)));
            self.process_single(cmd.trim());
            return;
        }
        let val = convert_value(val);
        self.push_line(&format!("{name} = {val}"));
    }
}

// ==================== Helpers ====================

fn strip_prefix_word<'a>(line: &'a str, word: &str) -> Option<&'a str> {
    let rest = line.strip_prefix(word)?;
    if rest.is_empty() || rest.starts_with(' ') || rest.starts_with('\t') {
        Some(rest.trim_start())
    } else {
        None
    }
}

const fn is_in_string(_line: &str, _ch: char) -> bool {
    false
}

fn is_in_quotes(line: &str, ch: char) -> bool {
    let mut in_single = false;
    let mut in_double = false;
    for c in line.chars() {
        if c == '\'' && !in_double { in_single = !in_single; }
        if c == '"' && !in_single { in_double = !in_double; }
        if c == ch && !in_single && !in_double {
            return false; // found unquoted
        }
    }
    true // only found inside quotes
}

fn split_on_semicolons(line: &str) -> Vec<&str> {
    // Simple split — doesn't handle semicolons in strings
    line.split(';').collect()
}

fn parse_function_def(line: &str) -> Option<String> {
    // function name { ... or function name() { ... or name() { ...
    if let Some(rest) = strip_prefix_word(line, "function") {
        let name = rest.trim_end_matches('{').trim_end_matches('(').trim_end_matches(')').trim();
        if !name.is_empty() {
            return Some(name.to_string());
        }
    }
    if line.ends_with("() {") || line.ends_with("(){") {
        let name = line.split('(').next()?.trim();
        if !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_') {
            return Some(name.to_string());
        }
    }
    None
}

fn skip_declare_flags(s: &str) -> &str {
    let mut rest = s.trim();
    while rest.starts_with('-') {
        // Skip flag and its value
        if let Some(pos) = rest.find(' ') {
            rest = rest[pos..].trim();
        } else {
            return "";
        }
    }
    rest
}

fn parse_assignment(line: &str) -> Option<(&str, &str)> {
    // Must have = and the part before must be a valid variable name
    let eq_pos = line.find('=')?;
    let name = &line[..eq_pos];
    // No spaces before = and valid identifier
    if name.contains(' ') || name.is_empty() { return None; }
    if !name.chars().all(|c| c.is_alphanumeric() || c == '_') { return None; }
    // Skip array assignments like arr=(...)
    let val = &line[eq_pos+1..];
    Some((name, val))
}

fn convert_value(val: &str) -> String {
    let val = val.trim();
    if val.is_empty() {
        return "\"\"".to_string();
    }
    // Arithmetic: $((expr))
    if val.starts_with("$((") && val.ends_with("))") {
        let inner = &val[3..val.len()-2];
        return convert_arithmetic_expr(inner);
    }
    // Quoted string (must be at least 2 chars)
    if val.len() >= 2 &&
       ((val.starts_with('"') && val.ends_with('"')) ||
        (val.starts_with('\'') && val.ends_with('\''))) {
        let inner = &val[1..val.len()-1];
        let converted = convert_string_content(inner);
        return format!("\"{converted}\"");
    }
    // Array: (val1 val2 val3)
    if val.starts_with('(') && val.ends_with(')') && !val.starts_with("$(") {
        let inner = &val[1..val.len()-1];
        let items: Vec<String> = inner.split_whitespace()
            .map(convert_value)
            .collect();
        return format!("[{}]", items.join(", "));
    }
    // Command substitution: $(cmd) or `cmd`
    if val.starts_with("$(") && val.ends_with(')') {
        let cmd = &val[2..val.len()-1];
        return convert_command(cmd);
    }
    if val.starts_with('`') && val.ends_with('`') {
        let cmd = &val[1..val.len()-1];
        return convert_command(cmd);
    }
    // Variable reference: $VAR or ${VAR}
    if val.starts_with('$') {
        return convert_var_ref(val);
    }
    // Number
    if val.parse::<i64>().is_ok() || val.parse::<f64>().is_ok() {
        return val.to_string();
    }
    // Bare word → string
    format!("\"{val}\"")
}

fn convert_var_ref(val: &str) -> String {
    let val = val.trim_start_matches('$');
    // ${VAR} → VAR
    if val.starts_with('{') && val.ends_with('}') {
        let inner = &val[1..val.len()-1];
        // ${VAR:-default}
        if let Some((name, default)) = inner.split_once(":-") {
            return format!("{name} || {}", convert_value(default));
        }
        // ${VAR:+alt}
        if let Some((name, _alt)) = inner.split_once(":+") {
            return name.to_string();
        }
        // ${#VAR} → len(VAR)
        if let Some(rest) = inner.strip_prefix('#') {
            return format!("len({rest})");
        }
        // ${VAR%pattern}, ${VAR#pattern} etc. → TODO
        if inner.contains('%') || inner.contains('#') {
            return format!("{} # TODO: parameter expansion", inner.split(['%', '#']).next().unwrap_or(inner));
        }
        return inner.to_string();
    }
    // $1, $2 etc. → args()[0], args()[1]
    if val.chars().all(|c| c.is_ascii_digit()) {
        let n: usize = val.parse().unwrap_or(0);
        if n == 0 {
            return "args()".to_string();
        }
        return format!("args()[{}]", n - 1);
    }
    // $@ or $* → args()
    if val == "@" || val == "*" {
        return "args()".to_string();
    }
    // $# → len(args())
    if val == "#" {
        return "len(args())".to_string();
    }
    // $? → last command exit status — use .status on the result
    if val == "?" {
        return "last_result.status # TODO: store command result in a variable first".to_string();
    }
    // $! → PID of last background process
    if val == "!" {
        return "# TODO: $! — use thread() and wait() instead".to_string();
    }
    // $$ → current PID
    if val == "$" {
        return "pid()".to_string();
    }
    // Simple variable
    val.to_string()
}

fn convert_string_content(s: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = s.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '$' {
            i += 1;
            if i >= chars.len() {
                result.push('$');
                break;
            }
            if chars[i] == '{' {
                // ${...}
                let start = i + 1;
                while i < chars.len() && chars[i] != '}' { i += 1; }
                let var_name: String = chars[start..i].iter().collect();
                i += 1; // skip }
                // Simple var ref
                if var_name.chars().all(|c| c.is_alphanumeric() || c == '_') {
                    result.push('{');
                    result.push_str(&var_name);
                    result.push('}');
                } else {
                    use std::fmt::Write;
                    let _ = write!(result, "{{{var_name}}} # TODO: complex expansion");
                }
            } else if chars[i] == '(' {
                // $(command)
                let start = i + 1;
                let mut depth = 1;
                i += 1;
                while i < chars.len() && depth > 0 {
                    if chars[i] == '(' { depth += 1; }
                    if chars[i] == ')' { depth -= 1; }
                    i += 1;
                }
                let cmd: String = chars[start..i-1].iter().collect();
                result.push('{');
                result.push_str(&convert_command(&cmd));
                result.push('}');
            } else if chars[i].is_alphanumeric() || chars[i] == '_' {
                // $VAR
                let start = i;
                while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_') { i += 1; }
                let var_name: String = chars[start..i].iter().collect();
                result.push('{');
                result.push_str(&var_name);
                result.push('}');
            } else {
                result.push('$');
                result.push(chars[i]);
                i += 1;
            }
        } else if chars[i] == '\\' {
            i += 1;
            if i < chars.len() {
                match chars[i] {
                    'n' => result.push_str("\\n"),
                    't' => result.push_str("\\t"),
                    '"' => result.push_str("\\\""),
                    '\\' => result.push_str("\\\\"),
                    c => { result.push('\\'); result.push(c); }
                }
                i += 1;
            }
        } else {
            result.push(chars[i]);
            i += 1;
        }
    }
    result
}

fn convert_condition(cond: &str) -> String {
    let cond = cond.trim();
    // [[ expr ]]
    if cond.starts_with("[[") && cond.ends_with("]]") {
        let inner = cond[2..cond.len()-2].trim();
        return convert_test_expr(inner);
    }
    // [ expr ]
    if cond.starts_with('[') && cond.ends_with(']') {
        let inner = cond[1..cond.len()-1].trim();
        return convert_test_expr(inner);
    }
    // Command as condition — strip redirects, handle type/command
    let (clean, _redirects) = strip_redirects(cond);
    let clean = clean.trim();
    // Handle negation: ! command
    let (negated, inner) = clean.strip_prefix("! ")
        .map_or((false, clean), |rest| (true, rest.trim()));
    let parts: Vec<&str> = inner.split_whitespace().collect();
    let result = if !parts.is_empty() && (parts[0] == "type" || parts[0] == "command") {
        let cmd_name = if parts[0] == "command" && parts.get(1) == Some(&"-v") {
            parts.get(2).unwrap_or(&"")
        } else {
            parts.get(1).unwrap_or(&"")
        };
        format!("which({})", convert_value(cmd_name))
    } else {
        convert_command(inner)
    };
    if negated {
        format!("!{result}")
    } else {
        result
    }
}

fn convert_test_expr(expr: &str) -> String {
    let expr = expr.trim();

    // Logical operators
    if let Some(pos) = find_logical_op(expr, "&&") {
        let left = convert_test_expr(&expr[..pos]);
        let right = convert_test_expr(&expr[pos+2..]);
        return format!("{left} && {right}");
    }
    if let Some(pos) = find_logical_op(expr, "||") {
        let left = convert_test_expr(&expr[..pos]);
        let right = convert_test_expr(&expr[pos+2..]);
        return format!("{left} || {right}");
    }

    // Negation
    if let Some(rest) = expr.strip_prefix("! ") {
        return format!("!{}", convert_test_expr(rest));
    }

    let parts: Vec<&str> = expr.splitn(3, ' ').collect();

    // Unary tests
    if parts.len() == 2 {
        let (flag, arg) = (parts[0], convert_expr(parts[1]));
        return match flag {
            "-f" => format!("is_file({arg})"),
            "-d" => format!("is_dir({arg})"),
            "-e" => format!("exists({arg})"),
            "-z" => format!("len({arg}) == 0"),
            "-n" => format!("len({arg}) > 0"),
            "-r" | "-w" | "-x" => format!("exists({arg}) # TODO: {flag} permission check"),
            _ => format!("# TODO: test {flag} {arg}"),
        };
    }

    // Binary tests
    if parts.len() >= 3 {
        let left = convert_expr(parts[0]);
        let op = parts[1];
        let right = convert_expr(parts[2]);
        return match op {
            "==" | "=" | "-eq" => format!("{left} == {right}"),
            "!=" | "-ne" => format!("{left} != {right}"),
            "-lt" => format!("{left} < {right}"),
            "-le" => format!("{left} <= {right}"),
            "-gt" => format!("{left} > {right}"),
            "-ge" => format!("{left} >= {right}"),
            "=~" => format!("match({left}, {right})"),
            _ => format!("{left} {op} {right} # TODO: unknown operator"),
        };
    }

    // Single value (truthy check)
    if parts.len() == 1 {
        return convert_expr(parts[0]);
    }

    format!("# TODO: test expression: {expr}")
}

fn find_logical_op(expr: &str, op: &str) -> Option<usize> {
    // Find op not inside quotes or brackets
    let bytes = expr.as_bytes();
    let op_bytes = op.as_bytes();
    let mut depth = 0;
    let mut in_quote = false;
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' || bytes[i] == b'\'' { in_quote = !in_quote; }
        if !in_quote {
            if bytes[i] == b'[' || bytes[i] == b'(' { depth += 1; }
            if bytes[i] == b']' || bytes[i] == b')' { depth -= 1; }
            if depth == 0 && i + op_bytes.len() <= bytes.len() && &bytes[i..i+op_bytes.len()] == op_bytes {
                return Some(i);
            }
        }
        i += 1;
    }
    None
}

fn convert_expr(s: &str) -> String {
    let s = s.trim();
    if s.is_empty() { return "\"\"".to_string(); }

    // Arithmetic: $((expr))
    if s.starts_with("$((") && s.ends_with("))") {
        let inner = &s[3..s.len()-2];
        return convert_arithmetic_expr(inner);
    }
    // Command substitution
    if s.starts_with("$(") && s.ends_with(')') {
        let cmd = &s[2..s.len()-1];
        return convert_command(cmd);
    }
    if s.starts_with('`') && s.ends_with('`') {
        let cmd = &s[1..s.len()-1];
        return convert_command(cmd);
    }
    // Variable
    if s.starts_with('$') {
        return convert_var_ref(s);
    }
    // Quoted string (must be at least 2 chars)
    if s.len() >= 2 && s.starts_with('"') && s.ends_with('"') {
        let inner = &s[1..s.len()-1];
        return format!("\"{}\"", convert_string_content(inner));
    }
    if s.len() >= 2 && s.starts_with('\'') && s.ends_with('\'') {
        let inner = &s[1..s.len()-1];
        return format!("'{inner}'");
    }
    // Number
    if s.parse::<i64>().is_ok() {
        return s.to_string();
    }
    // Bare word
    s.to_string()
}

fn convert_arithmetic_expr(expr: &str) -> String {
    let expr = expr.trim();
    // Replace bash variable references (no $ needed in $(()))
    let mut result = String::new();
    let chars: Vec<char> = expr.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '$' {
            i += 1;
            let start = i;
            while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_') { i += 1; }
            let var: String = chars[start..i].iter().collect();
            result.push_str(&var);
        } else {
            result.push(chars[i]);
            i += 1;
        }
    }
    result
}

fn convert_arithmetic_stmt(expr: &str) -> String {
    // (( i++ )) → i++
    // (( i = i + 1 )) → i = i + 1
    // (( i += 5 )) → i += 5
    convert_arithmetic_expr(expr)
}

fn convert_for_iter(iter: &str) -> String {
    let iter = iter.trim().trim_end_matches(';').trim();
    // $(seq 1 10) → range(1, 10)
    if (iter.starts_with("$(") && iter.ends_with(')')) || (iter.starts_with('`') && iter.ends_with('`')) {
        let cmd = if iter.starts_with("$(") {
            &iter[2..iter.len()-1]
        } else {
            &iter[1..iter.len()-1]
        };
        let cmd = cmd.trim();
        if cmd.starts_with("seq ") {
            let parts: Vec<&str> = cmd.split_whitespace().collect();
            if parts.len() == 3 {
                return format!("range({}, {})", parts[1], parts[2]);
            }
            if parts.len() == 2 {
                return format!("range(1, {})", parts[1]);
            }
        }
    }
    // {1..10} → range(1, 10)
    if iter.starts_with('{') && iter.ends_with('}') && iter.contains("..") {
        let inner = &iter[1..iter.len()-1];
        if let Some((start, end)) = inner.split_once("..") {
            return format!("range({}, {})", start.trim(), end.trim());
        }
    }
    // Bare list: word1 word2 word3 → ["word1", "word2", "word3"]
    if !iter.starts_with('$') && !iter.starts_with('"') && iter.contains(' ') {
        let items: Vec<String> = iter.split_whitespace()
            .map(convert_value)
            .collect();
        return format!("[{}]", items.join(", "));
    }
    convert_expr(iter)
}

fn convert_c_for(inner: &str) -> Vec<String> {
    // i=0; i<N; i++ → init, while cond (update injected via PENDING_UPDATE)
    let parts: Vec<&str> = inner.split(';').collect();
    if parts.len() == 3 {
        let init = convert_arithmetic_stmt(parts[0].trim());
        let cond = convert_arithmetic_expr(parts[1].trim());
        // Update part is handled by extract_c_for_update separately
        vec![
            init,
            format!("while {cond}"),
        ]
    } else {
        vec![format!("# TODO: C-style for: {inner}")]
    }
}

/// Extract the update part of a C-style for loop (e.g., "i++")
fn extract_c_for_update(line: &str) -> Option<String> {
    let start = line.find("((")?;
    let end = line.rfind("))")?;
    let inner = line[start+2..end].trim();
    let parts: Vec<&str> = inner.split(';').collect();
    if parts.len() == 3 {
        Some(convert_arithmetic_stmt(parts[2].trim()))
    } else {
        None
    }
}

fn convert_pipe_chain(line: &str) -> String {
    let parts: Vec<&str> = line.split(" | ").collect();
    let converted: Vec<String> = parts.iter().map(|p| convert_command(p.trim())).collect();
    converted.join(" -> ")
}

fn convert_command_ctx(cmd: &str, _user_fns: &[String]) -> String {
    // Resolution is applied in push_line, so just convert
    convert_command(cmd)
}

/// Apply ! or !! resolution to function calls based on whether they're user-defined or system builtins
fn apply_resolution(code: &str, user_fns: &[String]) -> String {
    let mut result = String::new();
    let chars: Vec<char> = code.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        // Look for pattern: identifier followed by (
        if chars[i].is_ascii_alphabetic() || chars[i] == '_' {
            let start = i;
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let name: String = chars[start..i].iter().collect();
            result.push_str(&name);
            // Check if followed by (
            if i < chars.len() && chars[i] == '(' {
                let lower = name.to_ascii_lowercase();
                if user_fns.contains(&lower) {
                    result.push('!');
                } else if PURE_BUILTINS.contains(&lower.as_str()) {
                    result.push('!');
                    result.push('!');
                }
                // exe call — no modifier
            }
        } else {
            result.push(chars[i]);
            i += 1;
        }
    }
    result
}

fn convert_command(cmd: &str) -> String {
    let cmd = cmd.trim();
    if cmd.is_empty() { return String::new(); }

    // Handle && and ||
    if let Some(pos) = find_logical_op(cmd, "&&") {
        let left = convert_command(cmd[..pos].trim_end());
        let right = convert_command(cmd[pos+2..].trim_start());
        return format!("{left} && {right}");
    }
    if let Some(pos) = find_logical_op(cmd, "||") {
        let left = convert_command(cmd[..pos].trim_end());
        let right = convert_command(cmd[pos+2..].trim_start());
        return format!("{left} || {right}");
    }

    // Strip redirections (> file, 2>&1, etc.)
    let (cmd, redirects) = strip_redirects(cmd);
    let cmd = cmd.trim();

    let parts: Vec<&str> = cmd.split_whitespace().collect();
    if parts.is_empty() { return String::new(); }

    let name = parts[0];
    let args = &parts[1..];

    // Special builtins
    match name {
        "echo" => {
            let msg = if args.is_empty() { "\"\"".to_string() } else { convert_value(&args.join(" ")) };
            let mut result = format!("println({msg})");
            if !redirects.is_empty() {
                    use std::fmt::Write;
                    let _ = write!(result, " # TODO: redirects: {redirects}");
                }
            return result;
        }
        "cd" => {
            let dir = if args.is_empty() { "home()".to_string() } else { convert_value(args[0]) };
            return format!("cd({dir})");
        }
        "test" => {
            return convert_test_expr(&args.join(" "));
        }
        "type" | "command" => {
            // bash: type cmd / command -v cmd → check if command exists
            let cmd_name = if name == "command" && args.first() == Some(&"-v") {
                args.get(1).unwrap_or(&"")
            } else {
                args.first().unwrap_or(&"")
            };
            let mut result = format!("which({})", convert_value(cmd_name));
            if !redirects.is_empty() {
                result.push_str(" # stderr suppressed");
            }
            return result;
        }
        "printf" => {
            // printf "fmt" args → print(format string)
            let fmt_args: Vec<String> = args.iter().map(|a| convert_value(a)).collect();
            return format!("printf({})", fmt_args.join(", "));
        }
        "true" => return "true".to_string(),
        "false" => return "false".to_string(),
        _ => {}
    }

    // Generic command → function call
    let converted_args: Vec<String> = args.iter().map(|a| convert_value(a)).collect();
    let mut result = if converted_args.is_empty() {
        format!("{name}()")
    } else {
        format!("{name}({})", converted_args.join(", "))
    };

    if !redirects.is_empty() {
        let redirect = redirects.trim();
        if redirect == "2>/dev/null" || redirect == "2> /dev/null" {
            result.push_str(" # stderr suppressed — check .err if needed");
        } else if redirect == "2>&1" {
            result.push_str(" # stderr merged — access via .err on result");
        } else if redirect == ">&2" || redirect.starts_with(">&2") {
            result = result.replace("println(", "errprintln(").replace("print(", "errprint(");
        } else if redirect.starts_with(">>") {
            let file = redirect.trim_start_matches(">>").trim();
            {
                use std::fmt::Write;
                let _ = write!(result, " # TODO: append output to {file} — use append()");
            }
        } else if redirect.starts_with('>') {
            let file = redirect.trim_start_matches('>').trim();
            {
                use std::fmt::Write;
                let _ = write!(result, " # TODO: write output to {file} — use write()");
            }
        } else if redirect.starts_with('<') {
            result.push_str(" # TODO: input redirect — use exec_in()");
        } else {
            {
                use std::fmt::Write;
                let _ = write!(result, " # TODO: redirect: {redirect}");
            }
        }
    }

    result
}

fn strip_redirects(cmd: &str) -> (&str, String) {
    // Find redirections: 2>&1, 2>/dev/null, >> file, > file, < file
    // Scan from right to find the start of redirections
    let mut best_pos = cmd.len();
    for pattern in &[" 2>&1", " 2>/dev/null", " 2>", " >&2", " >>", " > ", " < "] {
        if let Some(pos) = cmd.find(pattern) {
            best_pos = best_pos.min(pos);
        }
    }
    // Also check for > not preceded by another >
    if let Some(pos) = cmd.find(" >") {
        // Make sure it's not >>
        let after = &cmd[pos+2..];
        if pos < best_pos && !after.starts_with('>') {
            best_pos = pos;
        }
    }
    if best_pos < cmd.len() {
        (&cmd[..best_pos], cmd[best_pos..].trim().to_string())
    } else {
        (cmd, String::new())
    }
}

/// Find the closing ) of a case pattern, ignoring ) inside quotes or subshells
fn find_case_pattern_end(line: &str) -> Option<usize> {
    let mut in_single = false;
    let mut in_double = false;
    let mut depth = 0;
    for (i, c) in line.chars().enumerate() {
        match c {
            '\'' if !in_double => in_single = !in_single,
            '"' if !in_single => in_double = !in_double,
            '(' if !in_single && !in_double => depth += 1,
            ')' if !in_single && !in_double => {
                if depth > 0 {
                    depth -= 1;
                } else {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

fn convert_case_pattern(pattern: &str) -> String {
    let pattern = pattern.trim();
    // OR patterns: a|b|c → # TODO: multiple match patterns
    if pattern.contains('|') {
        let first = pattern.split('|').next().unwrap_or(pattern).trim();
        let converted = convert_single_pattern(first);
        return format!("{converted} # TODO: OR pattern — original: {pattern}");
    }
    // Glob patterns: *.txt, etc.
    if pattern.contains('*') && pattern != "*" {
        return format!("\"{pattern}\" # TODO: glob pattern");
    }
    convert_single_pattern(pattern)
}

fn convert_single_pattern(pattern: &str) -> String {
    if pattern.starts_with('"') || pattern.starts_with('\'') {
        return convert_value(pattern);
    }
    if pattern.parse::<i64>().is_ok() {
        return pattern.to_string();
    }
    format!("\"{pattern}\"")
}
